name: Publish Package

on:
  release:
    types: [created]

defaults:
  run:    
    working-directory: sample-packages/npm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm i
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      # - run: npm cache clean
      - run: npm install --cache /tmp/empty-cache
      - run: npm ci
      - run: |
          npm config list
          echo "----"
          cat > .npmrc
          # echo _auth = ${{ secrets.PAT }} >> .npmrc
          echo always-auth = true >> .npmrc
          echo email = laura.armitage@bjss.com >> .npmrc
          echo @larmitage-bjss:registry="https://npm.pkg.github.com/" >> .npmrc
          # echo //npm.pkg.github.com/:username=larmitage-bjss >> .npmrc
          # echo //npm.pkg.github.com/:_password=${{ secrets.PAT }} >> .npmrc
          echo //npm.pkg.github.com/:always-auth=true >> .npmrc
          echo //npm.pkg.github.com/:_auth=${{ secrets.PAT }} >> .npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.PAT }} >> .npmrc
          echo userconfig = "/home/runner/work/_temp/.npmrc"  >> .npmrc
          echo "----"
          cat .npmrc
          echo "----"
          npm login --scope=@larmitage-bjss --registry=https://npm.pkg.github.com/ --loglevel verbose --no-package-lock --auth-type=legacy
      - run: npm publish
