name: Publish Package

on:
  release:
    types: [created]

defaults:
  run:    
    working-directory: sample-packages/npm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: |
          cat > .npmrc
          echo _auth = ${{ secrets.PAT }} >> .npmrc
          echo always-auth = true >> .npmrc
          echo email = laura.armitage@bjss.com >> .npmrc
          echo @larmitage-bjss:registry=https://npm.pkg.github.com >> .npmrc
          cat .npmrc
          npm login
      - run: npm publish
